### ISSUE TITLE
quagga: Syntax of "networks" in RIP is unclear

### ISSUE THREAD

**Issue by mimugmail** [opnsense/plugins#107]
Hi, 
tried to configure/test RIP, but I always get a "list validation error" no matter how I format the network, like 192.168.0.0 or 192.168.0.0/24.

What value does it expect?

**Comment by fabianfrz** [comment]
It is a Network with a CIDR notation netmask (latter should work)

**Comment by fabianfrz** [comment]
probably a validation message should be added

**Comment by mimugmail** [comment]
Hm, probably I misunderstood you.
I tried:
192.168.0.0
192.168.0.0/24
192.168.0.0 255.255.255.0

But everytime I got a "list validation error" with:

{
  "result": "failed",
  "validations": {
    "rip.networks": "list validation error"
  }
}

**Comment by fabianfrz** [comment]
That is strange, this are my networks (blanked out)
![image](https://cloud.githubusercontent.com/assets/3713914/24506206/089bced2-155d-11e7-869f-5ff8236e37df.png)

This one I can save.

**Comment by mimugmail** [comment]
Do you get dropdown list with some proposals when clicking in the field like with Passive Interfaces?

**Comment by fabianfrz** [comment]
no, I filled it in and pressed enter

**Comment by mimugmail** [comment]
Found it, you have to apply a "," at the end, also when there's only one network

{%   for network in OPNsense.quagga.rip.networks.split(',') %}

**Comment by fabianfrz** [comment]
`split` should always return a `list` (if the delimiter is not found, the `list` should have only one item).

```
>>> "1".split(",")
['1']
```

So this cannot be an issue. Or do I misunderstand something?

**Comment by mimugmail** [comment]
Correct, stupid guess. But definately I can only add it when I add "," after the /24

Also when I want to disable RIP again und uncheck it, I can't delete the network cause of a list validation error :)

**Comment by fabianfrz** [comment]
I fixed the help text. I hope that helps.

**Comment by mimugmail** [comment]
Thanks, there's still a small type "Netzworks".

But the thing with "," after the network is still not reproduceable on your side? Also when trying a new network you never used before like 242.245.242.0 or so?

**Comment by fabianfrz** [comment]
@mimugmail no, This network works on my side

**Comment by mimugmail** [comment]
Hm, I'll setup a new instance and test some different browsers ...
