### ISSUE TITLE
net/haproxy: Unable to configure rules

### ISSUE THREAD

**Issue by hemirosani** [opnsense/plugins#1225]
Hello,
I'm trying to configure a newly installed haproxy on the newest OPNsense Version (_19.1.2_).

I have created a server, a backend and also a frontend. Everything is saved well.
I also created a condition and then created a rule, using this condition. All this seems to work and is saved in the config.
But how do i attach this rule to the frontend. I found a field labelled as **'Regeln auswählen'** _in German_.
Thats the field i would expect to show me a selection drop down, containing my defined rule to be selected. But no drop down appears! If i type my rule name into the field manually, it is just cleared out again.
**So, my question is**: What am i doing wrong? Or is there an issue in the GUI?

_Note:_ I also checked the haproxy.config file. I find my server, backend and frontend, but no rule, condition or whatsever...

**Comment by mehmetali** [comment]
I have same problem. I checked api response and there is no entry about rules settings.
I also checked logs but I couldn't find any useful logs.

**Comment by boardyuk** [comment]
I'm getting the same issue. It's currently stopping me from migrating my HAProxy server to the OPNSense box at the moment as I use conditions and rules a fair bit.

I couldn't see anything in the logs, also inspecting the element seems to show that nothing is bound to the field so I don't know if this has just been missed accidentally.

**Comment by fraenki** [comment]
Hi all, thanks for the report. This regression was introduced because a new plugin feature requires some new core features, which were not available in OPNsense 19.1.2. Sorry about that. OPNsense 19.1.3 should fix this, please report back if it solves the issue for you.

**Comment by mimugmail** [comment]
Had the same issue, was able to fix it with removing _ in naming or rules.

**Comment by hemirosani** [comment]
So, just got 19.1.3 installed.
Unfortunately there is not any change in behaviour of the haproxy configuration. I still have the same problem when trying to add a rule to a front/backend.
Has the fix not been commited to 19.1.3?

**Comment by boardyuk** [comment]
I've also upgraded to 19.1.3 and have not got the required behaviour.

I've tried clearing cache to no effect, I've also used developer tools in both Firefox and Chrome on Windows to disable the cache and that doesn't work either. This is also the same on my Android phone using Firefox.

**Comment by fraenki** [comment]
Thanks for reporting back. Unfortunately I'm unable to reproduce this issue, I've tested this on 4 OPNsense boxes already. I cannot fix it as long as it's not reproducable, so I need you help.

Can anyone maybe post more details or share an animated GIF?

This is how it looks like on all my 4 testboxes:

![chrome-capture](https://user-images.githubusercontent.com/909706/54046077-9f6aeb00-41d3-11e9-9f9a-b1676fbac359.gif)

**Comment by fraenki** [comment]
> I have same problem. I checked api response and there is no entry about rules settings.

@mehmetali Would you please check the API results again? In frontent/backend you should find this item in the response:

![linkedact](https://user-images.githubusercontent.com/909706/54047781-418cd200-41d8-11e9-9d83-43bb4134004c.png)
(https://OPNSENSE/api/haproxy/settings/getFrontend/)

**Comment by hemirosani** [comment]
Strange! 

I did some intensive testing now. I defined more than one rule in the definition page.
Suddenly, a drop down selection is appearing in the front/backend configuration!!
But, the first (top) entry in the rules list is missing! I deleted the first entry and recreated it. Then it appears at the bottom of the list. Now it is selectable, but the new top entry is missing...

Hope this helps

**Comment by mehmetali** [comment]
I confirm this. After I added second rule, I can see 2th rule but first one is still missing.

> Strange!
> 
> I did some intensive testing now. I defined more than one rule in the definition page.
> Suddenly, a drop down selection is appearing in the front/backend configuration!!
> But, the first (top) entry in the rules list is missing! I deleted the first entry and recreated it. Then it appears at the bottom of the list. Now it is selectable, but the new top entry is missing...
> 
> Hope this helps

**Comment by fraenki** [comment]
@hemirosani @mehmetali Thanks, very useful indeed! :+1: 

I've found the issue, you can test the fix by applying it on the CLI:

```
opnsense-patch df1141878
```
(Important: Afterwards reload the page in your browser, so that the rules will be loaded again from the backend.)

Please let me know if this fixes the issue for you.

**Comment by mehmetali** [comment]
@fraenki Thank you for the patch. I can see and select all rules for backend pools and public services.

**Comment by hemirosani** [comment]
I can confirm: It work also on my installation!

Thank you very much...

**Comment by fraenki** [comment]
@hemirosani @mehmetali My patch restored the rules functionality, but it broke the sorting of rules... Ad provided a better fix, which can be applied like this:

```
opnsense-patch 3cff50b
```

(NOTE: If you have already applied the previous patch, you need to revert it by running `opnsense-patch df1141878` again.)

Thanks for your patience.
